### PR TITLE
Ukrainian and Russian translations

### PR DESCRIPTION
**Pull request by nitay-dp-ua**
Please add translations

### CODE REVIEW

**Comment by elbenfreund** [comment]
Thanks for your PR. Project Hamster is currently transitioning to a new codebase and it may take some time if someone familiar with the xfce4 plugin gets to review your contributions.

So far just a questions:
* Is it deliberate that you second commit contains just an image file illustrating the reported width issue?
if so, please remove this commit and make this PR strictly about the translation. But please feel free to open another PR with a fix for the width issue.

**Comment by nitay-dp-ua** [comment]
I remove commit with image, sorry, I newbie on github, thank you!

**Comment by elbenfreund** [comment]
Thank you for the fast adjustments and your contributions. Welcome to the hamster, btw :)

**Comment by aquaherd** [comment]
Thank you.

**Pull request merged**
